### ISSUE TITLE
Getting error in execution

### ISSUE THREAD

**Issue by nameisnot** [paraschopra/abstract-art-neural-network#3]
Getting the following error:

`TypeError: 'NoneType' object is not iterable`

At line:

`n,c = gen_new_image(128, 128, save=False, num_neurons=32)`

I am using python 3.6 on mac and latest version of **torch** on **IDLE**. 

What am I missing?

**Comment by paraschopra** [comment]
You'll have to give more details. There's no iteration happening in the line you've copy-pasted, the error is probably somewhere else.

Also, you might want to use Jupyter notebook (and not IDLE).

**Comment by nameisnot** [comment]
Okay, I will try Jupyter and will let you know.

PS. You are right! I had (first) copied and keyed in, and then also copy-pasted your code, when I encountered the error. And the libraries being imported are up to date (I believe) and are working in some other applications. Pls let me know if any other details are required. Thanks

**Comment by c7v** [comment]
Спасибо за код!

У меня при выполнении, вылетает ошибка, которая связана с классом NN

>>> n,c = gen_new_image(128, 128, save=False, num_neurons=32)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 2, in gen_new_image
NameError: name 'NN' is not defined
